namespace Sharky
{
    public enum UnitRole
    {
        None,
        Bait,
        Scout,
        PreBuild,
        Build,
        Proxy,
        Minerals,
        Gas,
        Defend,
        Attack,
        PreventGasSteal,
        PreventBuildingLand,
        Wall,
        Door,
        Harass,
        Support,
        Repair,
        SpawnLarva,
        SpreadCreep,
        Morph,
        Die,
        ChaseReaper,
        WallOff,
        Regenerate,
        Hide,
        Regroup,
        BlockExpansion,
        Leader
    }
}
