[assembly: System.Reflection.AssemblyCompanyAttribute("Sharknice")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("The Sharky Framework.  A StarCraft 2 API framework for creating StarCraft 2 bots")]
[assembly: System.Reflection.AssemblyProductAttribute("Sharky")]
[assembly: System.Reflection.AssemblyTitleAttribute("Sharky")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.*")]